### ISSUE TITLE
Reorganize: prophecy feedback, prophecies and weekly links

### ISSUE THREAD

**Issue by castellanocj1** [djotaku/prophecypracticum_django#21]
the current way of seeing a week's worth of prophecies, feedback and weekly links is too challenging.  Organizing them by date is too difficult to follow. Can they be organized by order in which each practicum happened? Right now, there have been 5 practicums to date. Can we organize them by practicum #?

**Comment by djotaku** [comment]
Is this for the admin pages or for the user's pages?

**Comment by castellanocj1** [comment]
Right now this is for the admin view. From the current feedback page, I have no good way of figuring out who's feedback goes to who.

This is currently the highest priority

**Comment by djotaku** [comment]
Thinking "aloud" about how I might solve this: 

- I think we need to add a field to the database for prophecy to add a field for the practicum number. 
- Challenge will be in figuring out how to programmatically increment this number

**Comment by djotaku** [comment]
Current idea is to assign a number at the time the matches are made. 

Easier than a number would be YYYYMMDD because that would be deterministic at the time of the match. Else I'd have to figure out how to figure out the last number and increment that by one.

Would it work if you had Practicum YYYYMMDD? 

They'd naturally sort since the least significant digit is the day of the month and so on.

**Comment by castellanocj1** [comment]
That is a better idea than number
