### ISSUE TITLE
New Practicum Week Status View

### ISSUE THREAD

**Issue by castellanocj1** [djotaku/prophecypracticum_django#26]
![image](https://user-images.githubusercontent.com/64316093/127785901-0cf89c59-59f1-45fd-9aa7-1c278d8d0ae1.png)

I need a way to see the status of all the users and what they have and haven't done; if they have done given a prophecies, if they have received a prophecy, if they have given feedback and if they have gotten feedback.

**Comment by djotaku** [comment]
OK, I think the easiest way for this will be to create a regular page for the admins that will have this data. I'm not sure an admin view could easily be created to show this. But will have to think more about admin page that is a combination of many databases. Needs some research.

In the meanwhile, will definitely depend upon solving #21 in order to go by the week

**Comment by djotaku** [comment]
done with pr #28
